### ISSUE TITLE
[BUG]Only able to make a 20 pound reduction?

### ISSUE THREAD

**Issue by btg611** [titus-studios-media/PureAir#37]
Hi,

When I move my brakes into the "Apply" position, the brake pipe needle only drops 20 pounds. I'm not sure if I'm doing something wrong, or if there is a way to change the maximum reduction, but as it stands it's very difficult to control my speed when moving downhill with any amount of cars using the train brakes.

To reproduce,  set up and wire the normal way as stated on the main page. Apply brakes. If moved into the "Emergency" position, the brake pipe will drop fully as intended, but normal applications stop when the brake pipe needle reaches 70 psi. It *should* continue to drop as long as the brake handle is in the apply position until returned to "Lap" on Manual Lapping systems, but you know that already.

Tried changing brake valve types to no avail. It does this on all engines I apply PureAir to as well.
Don't know if it's just me.

 - OS: Windows 10 Pro
 - Version 1809

-PowerTrain

**Comment by TitusStudiosMediaGroup** [comment]
Hi, 
Sorry for the late reply. 

This **_ISNT_** an issue with the PureAir Engine. You should contact your Locomotive Controller Developer for help on this issue.

Thank you.
^TSMG

**Comment by btg611** [comment]
So you're telling me it's an issue with PT Gamma then?

**Comment by TitusStudiosMediaGroup** [comment]
Yes, and or, user error.
